server:
  port: 8080
spring:
  freemarker:
    cache: false
    settings:
      template_exception_handler: rethrow
      number_format: 0.##

# 配置mapper.xml位置，这个位置可以在pom.xml里配置
mybatis-plus:
  mapper-locations: classpath:/*Mapper.xml

datasource_driver: com.mysql.cj.jdbc.Driver
datasource_url: jdbc:mysql://localhost:3306/pybbs?useSSL=false&characterEncoding=utf8
datasource_username: root
datasource_password:

# 想看mybatis执行的sql的时候，去掉下面这段的注释
#logging:
#  level:
#    co:
#      yiiu:
#        pybbs:
#          mapper: debug
