server:
  port: 8080
spring:
  application:
    name: YIIU
  resources:
    static-locations:
    - file:./views/${site.theme}/static/
  freemarker:
    template-loader-path:
    - file:./views/${site.theme}/templates/
    cache: false
    settings:
      template_exception_handler: rethrow
      number_format: 0.##
  datasource:
    url: jdbc:mysql://localhost/yiiu?useSSL=false&characterEncoding=utf8
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false
  mail:
    host: smtp.qq.com
    username: xxoo@qq.com
    password: # 这里的密码是QQ邮箱的授权码
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  servlet:
    multipart:
      max-file-size: 2MB

site:
  name: YIIU
  intro: <h5>属于Java语言的bbs</h5><p>在这里，您可以提问，回答，分享，诉说，这是个属于Java程序员的社区，欢迎您的加入！</p>
  baseUrl: http://localhost:8080/ # 不要忘了后面的 '/'
  staticUrl: http://localhost:8080/static/images/upload/
  pageSize: 20
  uploadPath: ./views/${site.theme}/static/images/upload/
  theme: default
  search: false
  GA: #Google Analytics ID
  googleZZ: # google站长meta标签content值
  baiduTJ: # 百度统计ID
  baiduZZ: # 百度站长meta标签content值
  cookie:
    domain: localhost
    userName: remember-me
    userMaxAge: 30 # 天
    adminUserName: admin-remember-me
    adminUserMaxAge: 30 # 天
  oauth2:
    github:
      clientId: becbb7ea2f472f12bb59
      clientSecret: 009f598e9c0e32cc050bb5ef887fff09d1c0e4ae
      callbackUrl: https://fea612d0.ngrok.io/oauth2/github/callback

mail:
  register:
    subject: 注册验证码 - ${site.name}
    content: |
      <p>您好</p>
      <p>&nbsp;&nbsp;您的验证码为 <span style='color: red;'>$\{genCode!}</span> , 请在10分钟内使用！</p><br>
      <small>本邮件为系统发出，请不要评论</small>
  commentTopic:
    subject: 话题被评论 - ${site.name}
    content: |
      <p>您好</p>
      <p>&nbsp;&nbsp;$\{username!} 评论了您的话题 <a href='$\{domain!}topic/$\{topic.id}'>$\{topic.title!}</a></p>
      <div style='background-color: #fffbc1; padding: 20px; border-radius: 5px;'>$\{content!}</div><br>
      <small>本邮件为系统发出，请不要评论</small>
  replyComment:
    subject: 评论被回复 - ${site.name}
    content: |
      <p>您好</p>
      <p>&nbsp;&nbsp;$\{username!} 回复了您在话题 <a href='$\{domain!}topic/$\{topic.id}'>$\{topic.title!}</a> 下的评论</p>
      <div style='background-color: #fffbc1; padding: 20px; border-radius: 5px;'>$\{content!}</div><br>
      <small>本邮件为系统发出，请不要评论</small>

log:
  template:
    createTopic: 创建话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    commentTopic: 评论话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    replyComment: 回复话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 下的评论
    editTopic: 编辑话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    deleteTopic: 删除话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    collectTopic: 收藏话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    deleteCollectTopic: 删除收藏的话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a>
    editComment: 编辑话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 下的评论
    deleteComment: 删除话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 下的评论
    upTopic: 给话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 点赞
    downTopic: 给话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 点踩
    upComment: 给话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 下的评论点赞
    downComment: 给话题 <a href='/topic/$\{topic.id}' target='_blank'>$\{topic.title}</a> 下的评论点踩