server:
  port: 8080
spring:
  resources:
    static-locations:
    - classpath:/${site.theme}/static
    - file:./views/${site.theme}/static
  freemarker:
    template-loader-path:
    - classpath:/${site.theme}/templates
    - file:./views/${site.theme}/templates
    cache: false
  datasource:
    url: jdbc:mysql://localhost/yiiu?useSSL=false&characterEncoding=utf8
    username: root
    password: 123123
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: ./indexes
  mvc:
    static-path-pattern: /static/**
  mail:
    host: smtp.qq.com
    username: xxoo@qq.com
    password: # 这里的密码是QQ邮箱的授权码
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  servlet:
    multipart:
      max-file-size: 2MB
site:
  name: YIIU
  intro: <h5>属于Java语言的bbs</h5><p>在这里，您可以提问，回答，分享，诉说，这是个属于Java程序员的社区，欢迎您的加入！</p>
  baseUrl: http://localhost:8080/
  staticUrl: http://localhost:8080/static/images/upload/
  pageSize: 20
  uploadPath: ./static/images/upload/
  theme: default
  search: true
  attempts: 5
  attemptsWaitTime: 15
  maxCreateTopic: 10
  userUploadSpaceSize: 50 # 单位MB
  cookie:
    domain: localhost
    attendanceMaxAge: 86400
    attendanceName: attendance